# Generated by Django 3.1 on 2021-02-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_auto_20210130_2256'),
        ('insurance', '0003_postthird_agree'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAccident',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address', models.CharField(default='', max_length=30, verbose_name='آدرس')),
                ('city', models.CharField(default='', max_length=30, verbose_name='شهر')),
                ('age', models.CharField(max_length=30, verbose_name='تاریخ تولد ')),
                ('mobile', models.CharField(default='', max_length=30, verbose_name='موبایل')),
                ('kind', models.CharField(max_length=30, verbose_name='نوع خودرو')),
                ('model', models.CharField(default='', max_length=11, verbose_name='مدل خودرو')),
                ('system', models.CharField(default='', max_length=30, verbose_name='سیستم خودرو')),
                ('birth_of_insurance', models.CharField(max_length=30, verbose_name='تاریخ بیمه')),
                ('years_of_sale', models.CharField(default='', max_length=11, verbose_name='تخفیف بیمه')),
                ('agree', models.BooleanField(default=True, verbose_name='با کلیه شرایط شرکت موافقم')),
            ],
        ),
        migrations.CreateModel(
            name='PostBarbarry',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address', models.CharField(default='', max_length=30, verbose_name='آدرس')),
                ('city', models.CharField(default='', max_length=30, verbose_name='شهر')),
                ('age', models.CharField(max_length=30, verbose_name='تاریخ تولد ')),
                ('mobile', models.CharField(default='', max_length=30, verbose_name='موبایل')),
                ('kind', models.CharField(max_length=30, verbose_name='نوع خودرو')),
                ('model', models.CharField(default='', max_length=11, verbose_name='مدل خودرو')),
                ('system', models.CharField(default='', max_length=30, verbose_name='سیستم خودرو')),
                ('birth_of_insurance', models.CharField(max_length=30, verbose_name='تاریخ بیمه')),
                ('years_of_sale', models.CharField(default='', max_length=11, verbose_name='تخفیف بیمه')),
                ('agree', models.BooleanField(default=True, verbose_name='با کلیه شرایط شرکت موافقم')),
            ],
        ),
        migrations.CreateModel(
            name='PostBody',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address', models.CharField(default='', max_length=30, verbose_name='آدرس')),
                ('city', models.CharField(default='', max_length=30, verbose_name='شهر')),
                ('age', models.CharField(max_length=30, verbose_name='تاریخ تولد ')),
                ('mobile', models.CharField(default='', max_length=30, verbose_name='موبایل')),
                ('kind', models.CharField(max_length=30, verbose_name='نوع خودرو')),
                ('model', models.CharField(default='', max_length=11, verbose_name='مدل خودرو')),
                ('system', models.CharField(default='', max_length=30, verbose_name='سیستم خودرو')),
                ('birth_of_insurance', models.CharField(max_length=30, verbose_name='تاریخ بیمه')),
                ('years_of_sale', models.CharField(default='', max_length=11, verbose_name='تخفیف بیمه')),
                ('agree', models.BooleanField(default=True, verbose_name='با کلیه شرایط شرکت موافقم')),
            ],
        ),
        migrations.CreateModel(
            name='PostDoctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address', models.CharField(default='', max_length=30, verbose_name='آدرس')),
                ('city', models.CharField(default='', max_length=30, verbose_name='شهر')),
                ('age', models.CharField(max_length=30, verbose_name='تاریخ تولد ')),
                ('mobile', models.CharField(default='', max_length=30, verbose_name='موبایل')),
                ('kind', models.CharField(max_length=30, verbose_name='نوع خودرو')),
                ('model', models.CharField(default='', max_length=11, verbose_name='مدل خودرو')),
                ('system', models.CharField(default='', max_length=30, verbose_name='سیستم خودرو')),
                ('birth_of_insurance', models.CharField(max_length=30, verbose_name='تاریخ بیمه')),
                ('years_of_sale', models.CharField(default='', max_length=11, verbose_name='تخفیف بیمه')),
                ('agree', models.BooleanField(default=True, verbose_name='با کلیه شرایط شرکت موافقم')),
            ],
        ),
        migrations.CreateModel(
            name='PostFire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address', models.CharField(default='', max_length=30, verbose_name='آدرس')),
                ('city', models.CharField(default='', max_length=30, verbose_name='شهر')),
                ('age', models.CharField(max_length=30, verbose_name='تاریخ تولد ')),
                ('mobile', models.CharField(default='', max_length=30, verbose_name='موبایل')),
                ('kind', models.CharField(max_length=30, verbose_name='نوع خودرو')),
                ('model', models.CharField(default='', max_length=11, verbose_name='مدل خودرو')),
                ('system', models.CharField(default='', max_length=30, verbose_name='سیستم خودرو')),
                ('birth_of_insurance', models.CharField(max_length=30, verbose_name='تاریخ بیمه')),
                ('years_of_sale', models.CharField(default='', max_length=11, verbose_name='تخفیف بیمه')),
                ('agree', models.BooleanField(default=True, verbose_name='با کلیه شرایط شرکت موافقم')),
            ],
        ),
        migrations.CreateModel(
            name='PostOmar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address', models.CharField(default='', max_length=30, verbose_name='آدرس')),
                ('city', models.CharField(default='', max_length=30, verbose_name='شهر')),
                ('age', models.CharField(max_length=30, verbose_name='تاریخ تولد ')),
                ('mobile', models.CharField(default='', max_length=30, verbose_name='موبایل')),
                ('kind', models.CharField(max_length=30, verbose_name='نوع خودرو')),
                ('model', models.CharField(default='', max_length=11, verbose_name='مدل خودرو')),
                ('system', models.CharField(default='', max_length=30, verbose_name='سیستم خودرو')),
                ('birth_of_insurance', models.CharField(max_length=30, verbose_name='تاریخ بیمه')),
                ('years_of_sale', models.CharField(default='', max_length=11, verbose_name='تخفیف بیمه')),
                ('agree', models.BooleanField(default=True, verbose_name='با کلیه شرایط شرکت موافقم')),
            ],
        ),
        migrations.CreateModel(
            name='PostResponsibility',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address', models.CharField(default='', max_length=30, verbose_name='آدرس')),
                ('city', models.CharField(default='', max_length=30, verbose_name='شهر')),
                ('age', models.CharField(max_length=30, verbose_name='تاریخ تولد ')),
                ('mobile', models.CharField(default='', max_length=30, verbose_name='موبایل')),
                ('kind', models.CharField(max_length=30, verbose_name='نوع خودرو')),
                ('model', models.CharField(default='', max_length=11, verbose_name='مدل خودرو')),
                ('system', models.CharField(default='', max_length=30, verbose_name='سیستم خودرو')),
                ('birth_of_insurance', models.CharField(max_length=30, verbose_name='تاریخ بیمه')),
                ('years_of_sale', models.CharField(default='', max_length=11, verbose_name='تخفیف بیمه')),
                ('agree', models.BooleanField(default=True, verbose_name='با کلیه شرایط شرکت موافقم')),
            ],
        ),
    ]
