# Generated by Django 3.1 on 2021-02-09 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('computer', 'کامپیوتر'), ('internet', 'اینترنت'), ('program', 'برنامه نویسی'), ('photoshop', 'فتوشاپ'), ('office', 'آفیس'), ('english', 'زبان انگلیسی'), ('colculate', 'حسابداری')], default=('computer', 'کامپیوتر'), max_length=16, verbose_name='درس موردنظر ')),
                ('way', models.CharField(choices=[('go it', 'حضوری'), ('Online', 'آنلاین')], default=('go it', 'حضوری'), max_length=6, verbose_name='روش تدریس')),
                ('phoneNum', models.CharField(default='', max_length=11, verbose_name='تلفن ضروری')),
                ('address', models.TextField(default='', max_length=200, verbose_name='آدرس دقیق')),
                ('bio', models.TextField(default='', max_length=500, verbose_name='توضیحات')),
                ('agree', models.BooleanField(default=True, verbose_name='با کلیه شرایط شرکت موافقم')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
