# Generated by Django 3.1 on 2021-02-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedu',
            name='way',
            field=models.CharField(choices=[('حضوری', 'حضوری'), ('آنلاین', 'آنلاین')], default=('حضوری', 'حضوری'), max_length=6, verbose_name='روش تدریس'),
        ),
    ]
