# Generated by Django 3.1 on 2021-02-09 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', multiselectfield.db.fields.MultiSelectField(choices=[('ADSL', 'ADSL'), ('VDSL', 'Vdsl'), ('فیبرنوری', 'فیبرنوری'), ('بی سیم', 'بی سیم'), ('مارشال', 'مارشال')], max_length=32, verbose_name='سرویس ')),
                ('industry', multiselectfield.db.fields.MultiSelectField(choices=[('مخابرات', 'مخابرات'), ('ماکس نت', 'ماکس نت'), ('شاتل', 'شاتل'), ('آسیا تک', 'آسیا تک'), ('های وب', 'های وب')], max_length=35, verbose_name='شرکت ')),
                ('band', multiselectfield.db.fields.MultiSelectField(choices=[('1 M', ' M 1'), ('2 M', ' M 2'), ('4 M', ' M 4'), ('8 M', ' M 8'), ('16 M', ' M 16'), ('100 M', ' M 100')], max_length=26, verbose_name='پهنای باند ')),
                ('time', multiselectfield.db.fields.MultiSelectField(choices=[('ماهانه', 'ماهانه'), ('3 ماهه', '3 ماهه'), ('6 ماهه', '6 ماهه'), ('سالانه', 'سالانه')], max_length=27, verbose_name='مدت زمان ')),
                ('capacity', multiselectfield.db.fields.MultiSelectField(choices=[('10 G', '10 G'), ('20 G', '20 G'), ('30 G', '30 G'), ('100 G', '100 G')], max_length=20, verbose_name='حجم سرویس ')),
                ('modem', multiselectfield.db.fields.MultiSelectField(choices=[('بی سیم تک آنتنه', 'بی سیم تک آنتنه'), ('بی سیم دو آنتنه', 'بی سیم دو آنتنه'), ('فیبرنوری', 'فیبرنوری'), ('سیم کارت خور', 'سیم کارت خور')], max_length=53, verbose_name='مودم ')),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(default='', max_length=30, verbose_name='نام خانوادگی')),
                ('phoneNum', models.CharField(default='09', max_length=11, verbose_name='شماره تلفن ADSL')),
                ('address', models.TextField(default='', max_length=500, verbose_name='آدرس دقیق')),
                ('agree', models.BooleanField(default=True, verbose_name='با کلیه شرایط شرکت موافقم')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
